### ISSUE TITLE
Kipoi APARENT

### ISSUE THREAD

**Issue by robertzeibich** [johli/aparent#8] opened 2022-06-24 04:48 UTC
Hi, I am currently running Kipoi APARENT.

The provided example VCF file contains 15,077 variants, but the output only has 416 predictions for delta_logit_distal_prop and delta_logit_proximal_prop. I was expecting 15,077 predictions. Do you know why I only get 15,077 predictions?
<img width="272" alt="Kipoi APARENT" src="https://user-images.githubusercontent.com/73748542/175464214-45be6712-0d49-4633-a047-ae6f0bb2c2c3.PNG">

**Comment by Hoeze** [comment] 2022-06-24 08:41
fyi, as far as I know @johli did not review the Kipoi-APARENT version :)

**Comment by Hoeze** [comment] 2022-06-24 08:42
xref: https://github.com/kipoi/models/issues/342

**Comment by johli** [comment] 2022-06-24 16:12
I did not review the Kipoi version (my apologies) but let me know if there's anything I can help with on that side! Seems like the issue is getting resolved in the thread @Hoeze linked to though.

**Comment by robertzeibich** [comment] 2022-06-25 05:04
Thank you for getting back to me. I have already replied on [kipoi/models#342](https://github.com/kipoi/models/issues/342) and to be honest, I am still new to this, and therefore, I appreciate every support I get.

**Comment by Hoeze** [comment] 2022-07-04 10:18
> I did not review the Kipoi version (my apologies) but let me know if there's anything I can help with on that side!

Hi @johli, thank you for your offer!
I opened an issue to review the Kipoi APARENT predictions here:
https://github.com/kipoi/models/issues/346
If you have time, I would be very happy if you could have a quick look at it :)

**Closed as not planned** 2023-02-16 17:25 UTC
